.TH "Arcade::Exceptions::InvalidLibraryException" 3 "Sat Mar 28 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Exceptions::InvalidLibraryException \- Thrown when trying to use an invalid library file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InvalidLibraryException\&.hpp>\fP
.PP
Inherits \fBArcade::Exceptions::ArcadeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidLibraryException\fP (std::string const &message, std::string const &component)"
.br
.RI "Construct a new Invalid Library Exception object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Thrown when trying to use an invalid library file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Arcade::Exceptions::InvalidLibraryException::InvalidLibraryException (std::string const & message, std::string const & component)"

.PP
Construct a new Invalid Library Exception object\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP Message explaining the problem\&. 
.br
\fIcomponent\fP Additional information on where the problem occured\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
