.TH "Arcade::Games" 3 "Fri Apr 3 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Games
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGameModule\fP"
.br
.RI "Abstract class implementing key methods of the \fBIGameModule\fP interface\&. "
.ti -1c
.RI "class \fBCentipede\fP"
.br
.RI "\fBCentipede\fP game\&. "
.ti -1c
.RI "class \fBIGameModule\fP"
.br
.RI "Interface for the game modules used to handle games\&. "
.ti -1c
.RI "class \fBNibbler\fP"
.br
.RI "\fBNibbler\fP game\&. "
.ti -1c
.RI "class \fBPacman\fP"
.br
.RI "\fBPacman\fP game\&. "
.ti -1c
.RI "class \fBQix\fP"
.br
.RI "\fBQix\fP game\&. "
.ti -1c
.RI "class \fBSolarfox\fP"
.br
.RI "\fBSolarfox\fP game\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains elements related to the game libraries of the \fBArcade\fP project\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
