.TH "Arcade::Display::IDisplayModule" 3 "Thu Mar 26 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Display::IDisplayModule
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBArcade::Display::Libcaca\fP, \fBArcade::Display::SDL\fP, and \fBArcade::Display::SFML\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColors\fP { \fBDEFAULT\fP, \fBBLACK\fP, \fBRED\fP, \fBGREEN\fP, \fBYELLOW\fP, \fBBLUE\fP, \fBMAGENTA\fP, \fBCYAN\fP, \fBLIGHT_GRAY\fP, \fBDARK_GRAY\fP, \fBLIGHT_RED\fP, \fBLIGHT_GREEN\fP, \fBLIGHT_YELLOW\fP, \fBLIGHT_BLUE\fP, \fBLIGHT_MAGENTA\fP, \fBLIGHT_CYAN\fP, \fBWHITE\fP, \fBCOLORS_END\fP }"
.br
.ti -1c
.RI "enum \fBKeys\fP { \fBLEFT\fP, \fBRIGHT\fP, \fBUP\fP, \fBDOWN\fP, \fBZ\fP, \fBQ\fP, \fBS\fP, \fBD\fP, \fBA\fP, \fBE\fP, \fBW\fP, \fBX\fP, \fBSPACE\fP, \fBESCAPE\fP, \fBJ\fP, \fBK\fP, \fBU\fP, \fBI\fP, \fBM\fP, \fBR\fP, \fBENTER\fP, \fBKEYS_END\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBreset\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBopen\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBisOpen\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBswitchToNextLib\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBswitchToPreviousLib\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBswitchToNextGame\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBswitchToPreviousGame\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBshouldBeRestarted\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBshouldGoToMenu\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBshouldExit\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBisKeyPressed\fP (IDisplayModule::Keys) const =0"
.br
.ti -1c
.RI "virtual bool \fBisKeyPressedOnce\fP (IDisplayModule::Keys) const =0"
.br
.ti -1c
.RI "virtual float \fBgetDelta\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBclear\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBrender\fP () const =0"
.br
.ti -1c
.RI "virtual char \fBgetKeyCode\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetColor\fP (IDisplayModule::Colors col)=0"
.br
.ti -1c
.RI "virtual void \fBputPixel\fP (float x, float y) const =0"
.br
.ti -1c
.RI "virtual void \fBputLine\fP (float x1, float y1, float x2, float y2) const =0"
.br
.ti -1c
.RI "virtual void \fBputRect\fP (float x, float y, float w, float h) const =0"
.br
.ti -1c
.RI "virtual void \fBputFillRect\fP (float x, float y, float w, float h) const =0"
.br
.ti -1c
.RI "virtual void \fBputCircle\fP (float x, float y, float rad) const =0"
.br
.ti -1c
.RI "virtual void \fBputFillCircle\fP (float x, float y, float rad) const =0"
.br
.ti -1c
.RI "virtual void \fBputText\fP (const std::string &text, unsigned int size, float x, float y) const =0"
.br
.ti -1c
.RI "virtual const std::string & \fBgetLibName\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
