.TH "Arcade::Games::Pacman" 3 "Thu Mar 26 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Games::Pacman
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBArcade::Games::AGameModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP () final"
.br
.ti -1c
.RI "void \fBupdate\fP (const \fBArcade::Display::IDisplayModule\fP &lib) final"
.br
.ti -1c
.RI "void \fBrender\fP (\fBArcade::Display::IDisplayModule\fP &lib) const final"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void Arcade::Games::Pacman::render (\fBArcade::Display::IDisplayModule\fP & lib) const\fC [final]\fP, \fC [virtual]\fP"
Default game implementation (out of order) 
.PP
Reimplemented from \fBArcade::Games::AGameModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
