.TH "Arcade::DLLoader" 3 "Wed Mar 25 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::DLLoader
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "template<class T > using \fBcreateLib_t\fP = std::unique_ptr< T >(*)(void)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDLLoader\fP (\fBDLLoader\fP const &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBDLLoader\fP const &)=delete"
.br
.ti -1c
.RI "template<class T > std::vector< std::pair< std::string, std::string > > \fBgetLibraries\fP (const std::string &dirPath) const"
.br
.ti -1c
.RI "template<class T > std::unique_ptr< T > \fBloadLibrary\fP (const std::string &path) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDLLoader\fP const  & \fBgetInstance\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
