.TH "Arcade::Exceptions::ArcadeException" 3 "Wed Mar 25 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Exceptions::ArcadeException
.SH SYNOPSIS
.br
.PP
.PP
Inherits runtime_error\&.
.PP
Inherited by \fBArcade::Exceptions::BadFileException\fP, \fBArcade::Exceptions::BadInstanciationException\fP, and \fBArcade::Exceptions::InvalidLibraryException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArcadeException\fP (std::string const &message, std::string const &component)"
.br
.ti -1c
.RI "std::string const  & \fBgetComponent\fP (void) const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
