.TH "Arcade::Display" 3 "Sat Mar 28 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Display
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBADisplayModule\fP"
.br
.RI "Abstract class adding utilities and an enum to the \fBIDisplayModule\fP interface\&. "
.ti -1c
.RI "class \fBIDisplayModule\fP"
.br
.RI "Interface for the display modules used to display things\&. "
.ti -1c
.RI "class \fBLibcaca\fP"
.br
.RI "\fBLibcaca\fP library\&. "
.ti -1c
.RI "class \fBSDL\fP"
.br
.RI "\fBSDL\fP library\&. "
.ti -1c
.RI "class \fBSFML\fP"
.br
.RI "\fBSFML\fP library\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains elements related to the display libraries of the \fBArcade\fP project\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
