.TH "Arcade::Core" 3 "Fri Mar 27 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Core \- \fBCore\fP class that handles all the interactions between the library modules and the game modules\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Core\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCore\fP (const std::string &startLibraryPath)"
.br
.RI "Construct a new \fBCore\fP object\&. "
.ti -1c
.RI "void \fBplay\fP ()"
.br
.RI "Starts the arcade program\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBCore\fP class that handles all the interactions between the library modules and the game modules\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Arcade::Core::Core (const std::string & startLibraryPath)\fC [explicit]\fP"

.PP
Construct a new \fBCore\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstartLibraryPath\fP The library path that will be first used when the program will be started\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
