.TH "Arcade::Exceptions" 3 "Fri Apr 3 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Exceptions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArcadeException\fP"
.br
.RI "Base exception class for this projects' exceptions\&. "
.ti -1c
.RI "class \fBBadFileException\fP"
.br
.RI "Thrown when looking up to an external file that is inexistant\&. "
.ti -1c
.RI "class \fBBadInstanciationException\fP"
.br
.RI "Thrown when library objects failed to be instanciated\&. "
.ti -1c
.RI "class \fBInvalidLibraryException\fP"
.br
.RI "Thrown when trying to use an invalid library file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains a loadout of exceptions that are used in the \fBArcade\fP project\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
