.TH "Arcade::Exceptions::ArcadeException" 3 "Sat Mar 28 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Exceptions::ArcadeException \- Base exception class for this projects' exceptions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ArcadeException\&.hpp>\fP
.PP
Inherits exception\&.
.PP
Inherited by \fBArcade::Exceptions::BadFileException\fP, \fBArcade::Exceptions::BadInstanciationException\fP, and \fBArcade::Exceptions::InvalidLibraryException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArcadeException\fP (std::string const &message, std::string const &component)"
.br
.RI "Construct a new \fBArcade\fP Exception object\&. "
.ti -1c
.RI "const char * \fBwhat\fP (void) const noexcept override"
.br
.RI "Gets the error message which describe why the exception occured\&. "
.ti -1c
.RI "std::string const  & \fBgetComponent\fP (void) const noexcept"
.br
.RI "Gets the name of component where the exception occured\&. "
.in -1c
.SH "Detailed Description"
.PP 
Base exception class for this projects' exceptions\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Arcade::Exceptions::ArcadeException::ArcadeException (std::string const & message, std::string const & component)"

.PP
Construct a new \fBArcade\fP Exception object\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP Message explaining the problem\&. 
.br
\fIcomponent\fP Additional information on where the problem occured\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string const& Arcade::Exceptions::ArcadeException::getComponent (void) const\fC [noexcept]\fP"

.PP
Gets the name of component where the exception occured\&. 
.PP
\fBReturns:\fP
.RS 4
The component name 
.RE
.PP

.SS "const char* Arcade::Exceptions::ArcadeException::what (void) const\fC [override]\fP, \fC [noexcept]\fP"

.PP
Gets the error message which describe why the exception occured\&. 
.PP
\fBReturns:\fP
.RS 4
The error message 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
