.TH "Arcade" 3 "Sat Mar 28 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDisplay\fP"
.br
.ti -1c
.RI " \fBExceptions\fP"
.br
.ti -1c
.RI " \fBGames\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCore\fP"
.br
.RI "\fBCore\fP class that handles all the interactions between the library modules and the game modules\&. "
.in -1c
.SH "Detailed Description"
.PP 
Default namespace for the project\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
