.TH "Arcade::Logger" 3 "Wed Mar 25 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Logger
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLogLevel\fP { \fBERROR\fP, \fBDEBUG\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP (const \fBLogger\fP &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBLogger\fP &)=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename \&.\&.\&. Args> static void \fBlog\fP (LogLevel level, Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "static void \fBsetLogLevel\fP (LogLevel level)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
