.TH "Arcade::Games::Pacman" 3 "Fri Apr 3 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arcade::Games::Pacman \- \fBPacman\fP game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pacman\&.hpp>\fP
.PP
Inherits \fBArcade::Games::AGameModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP () final"
.br
.RI "Resets and restarts the game\&. "
.ti -1c
.RI "void \fBupdate\fP (const \fBArcade::Display::IDisplayModule\fP &displayModule) final"
.br
.RI "Updates the game\&. "
.ti -1c
.RI "void \fBrender\fP (\fBArcade::Display::IDisplayModule\fP &displayModule) const final"
.br
.RI "Renders the \fBPacman\fP game on the display module\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBPacman\fP game\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Arcade::Games::Pacman::render (\fBArcade::Display::IDisplayModule\fP & displayModule) const\fC [final]\fP, \fC [virtual]\fP"

.PP
Renders the \fBPacman\fP game on the display module\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisplayModule\fP The display module that will be used to put things on a canvas\&. 
.RE
.PP

.PP
Reimplemented from \fBArcade::Games::AGameModule\fP\&.
.SS "void Arcade::Games::Pacman::update (const \fBArcade::Display::IDisplayModule\fP & lib)\fC [final]\fP, \fC [virtual]\fP"

.PP
Updates the game\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlib\fP The display module that will be used to get events that occured 
.RE
.PP

.PP
Implements \fBArcade::Games::IGameModule\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
