.TH "rectangle_s" 3 "Wed Mar 25 2020" "Version 1.0" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rectangle_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "Arcade::Display::IDisplayModule::Colors \fBcolor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Arcade from the source code\&.
